config/routes.rb
Rails.application.routes.draw do
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "students#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

# bundle exec rspec spec/requests/students_spec.rb

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, :last_name, :school_email, :major, :graduation_date, presence: true # Values can't be empty

    
    validates :school_email, uniqueness: { case_sensitive: false }   # Email has to be unique.
    validates :school_email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "is not a valid email." }
    validates :school_email, format: { with: /\A[\w+\-.]+@msudenver\.edu\z/i, message: "address is not a valid 'username@msudenver.edu' email." }

    has_one_attached :profile_picture, dependent: :purge_later

    VALID_MAJORS = ["Any Major", "Computer Engineering BS", "Computer Information Systems BS",
       "Computer Science BS", "Cybersecurity Major", "Data Science and Machine Learning Major"]

    validates :major, inclusion: { in: VALID_MAJORS, message: "%{value} is not a valid major" }

    validate :must_have_search_criteria

    private

    def must_have_search_criteria
        if major.blank? && graduation_date.blank?
            errors.add(:base, "Please select either a Major or enter a Graduation Date.")
        end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # def home
  # end

  # GET /students or /students.json
  # def index
  #   @students = Student.all

  #   if params[:student]
  #     major = params[:student][:major]
  #     graduation_option = params[:student][:graduation_date_option]
  #     date = params[:student][:graduation_date]

  #     @students = @students.where(major: major) if major.present?

  #     if graduation_option.present? && date.present?
  #       if graduation_option == 'before'
  #         @students = @students.where('graduation_date < ?', date)
  #       elsif graduation_option == 'after'
  #         @students = @students.where('graduation_date > ?', date)
  #       end
  #     end
  #   end
  # end

  # def index
  #   puts "\n\n>>>> All Params <<<<"
  #   params.each do |key, value|
  #     puts "#{key}: #{value}"
  #   end
  #   puts ">>>> End of Params <<<<\n\n"
  # end



  def index

    puts "\n\n>>>> All Params <<<<"
    params.each do |key, value|
      puts "#{key}: #{value}"
    end
    puts ">>>> End of Params <<<<\n\n"
  
    @students = [] # This will make sure every get request starts with empty list of students.
  
    if params[:show_all].present?
      @students = Student.all
    elsif params[:student].present?
      major = params[:student][:major]
      graduation_option = params[:student][:graduation_date_option]
      date = params[:student][:graduation_date]
  
      puts ">>>> Search Criteria:"
      puts "Major: #{major}"
      puts "Graduation Option: #{graduation_option}"
      puts "Graduation Date: #{date} \n\n"
  
      # Check for empty param values
      if major.blank? && graduation_option.blank? && date.blank?
        flash.now[:alert] = "Please provide at least one search criterion."
        @students = []  # Empty previous results if any.
      else
        
        @students = Student.all  # Prepare list of all students
        # check for major type or if "Any Major" found
        if major.present? && major != "Any Major"
          @students = @students.where(major: major)
          puts ">>>> Filtered by Major: #{major}"
        else
          puts ">>>> No specific major filter applied. 'Any Major' selected."
        end
  
        # check graduation date options
        if graduation_option.present? && date.present?
          if graduation_option == 'before'
            @students = @students.where('graduation_date < ?', date)
            puts ">>>> Filtered for Graduation Date Before: #{date}"
          elsif graduation_option == 'after'
            @students = @students.where('graduation_date > ?', date)
            puts ">>>> Filtered for Graduation Date After: #{date}"
          end
        end
      end
    else
      puts ">>>> No search parameters provided.\n"
    end
  
    # Show total number of resulting students
    puts ">>>> Resulting Students Count: #{@students.count} \n"
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :school_email, :major, :minor, :graduation_date, :profile_picture)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>YourApp</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <!-- Include Bootstrap CSS via CDN -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

   <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
   <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
 </head>

 <body>

 <nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="container" style="maxWidth: 98% !important; ">
   <a class="navbar-brand" href="#">
     <img src="<%= asset_path('msulogo.png') %>" alt="MSU Denver Logo" style="width: 100px; height: 40px;">
     MSU Denver
   </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNav">
     <ul class="navbar-nav ml-auto">
       <li class="nav-item" style="margin:0 40px">
       
       <a href="#"  style="text-decoration: none; color: inherit;">
       Home
      </a>
       </li>
       <li class="nav-item">
       <a href="#" style="text-decoration: none; color: inherit;">
       Account
      </a>
       </li>
     </ul>
   </div>
 </div>
</nav>


   <!-- Test bootstrap button to see if it works then remove-->
   <!--  <button type="button" class="btn btn-warning">Warning</button> -->
   <%= yield %>
 </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :school_email, style: "display: block" %>
    <%= form.text_field :school_email %>
  </div>

  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.text_field :major %>
  </div>

  <div>
    <%= form.label :minor, style: "display: block" %>
    <%= form.text_field :minor %>
  </div>

  <div>
    <%= form.label :graduation_date, style: "display: block" %>
    <%= form.date_field :graduation_date %>
  </div>

  <div style="margin : 20px 0;">
    <%= form.label :profile_picture %>
    <%= form.file_field :profile_picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_results.html.erb
<table class="table bg-dark border border-success border-2">
  <thead class="bg-dark bg-gradient text-white border-bottom-5">
    <tr class="bg-dark bg-gradient text-white">
      <th class="bg-grey text-primary fs-5 align-center "></th>
      <th class="bg-grey text-primary fs-3 ">First Name</th>
      <th class="text-primary fs-3 ">Last Name</th>
      <th class="text-primary fs-3 ">Major</th>
      <th class="text-primary fs-3 ">Graduation Date</th>
      <th class="text-primary fs-3 ">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each_with_index do |student, index| %>
      <tr class="table-gradient">
        <td class="bg-light border"><%= index + 1 %></td>
        <td class="bg-light border"><%= student.first_name %></td>
        <td class="bg-light border"><%= student.last_name %></td>
        <td class="bg-light border"><%= student.major %></td>
        <td class="bg-light border"><%= student.graduation_date.strftime("%B %d, %Y") if student.graduation_date %></td>
        <td class="bg-light border">
          <%= link_to 'Show', student_path(student), class: 'btn btn-info' %>
          <%= link_to 'Edit', edit_student_path(student), class: 'btn btn-warning' %>
          <%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/_search.html.erb
<%= form_with(model: student, url: students_path, method: :get, local: true) do |form| %>
  <% if flash[:alert] %>
    <div style="color: red">
      <h2><%= flash[:alert] %></h2>
    </div>
  <% end %>
  

  <div class="ms-2">
    <%= form.label :major, "Select Major", style: "display: block" %>
    <%= form.select :major, options_for_select(Student::VALID_MAJORS), { prompt: "Select Major" }, class: "form-control" %>
  </div>

  <div class="ms-2">
    <%= form.label :graduation_date_option, "Graduation Date Search", style: "display: block" %>
    <%= form.select :graduation_date_option, options_for_select([['Before', 'before'], ['After', 'after']]), { prompt: "Select Option" }, class: "form-control" %>
  </div>

  <div class="ms-2">
    <%= form.label :graduation_date, "Date", style: "display: block" %>
    <%= form.date_field :graduation_date %>
  </div>

  <p class="ms-2">Please enter search criteria to find students.</p>

  <div class="mb-3 ms-3 ">
    <%= form.submit "Search", class: "btn btn-primary px-5 w-10" %>
  </div>

<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id(student) %>" style="display: flex;">

<div class="left-section">
  <h2>Student Profile</h2>
    <p>
      <strong>First name:</strong>
      <%= student.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= student.last_name %>
    </p>

    <p>
      <strong>School email:</strong>
      <%= student.school_email %>
    </p>

    <p>
      <strong>Major:</strong>
      <%= student.major %>
    </p>

    <p>
      <strong>Minor:</strong>
      <%= student.minor %>
    </p>

    <p>
      <strong>Graduation date:</strong>
      <%= student.graduation_date %>
    </p>
  </div>

  <div class="right-section" style="margin: 40px;">
    <h3>Profile Picture:</h3>
    <% if student.profile_picture.attached? %>
      <%= image_tag student.profile_picture.variant(resize_to_limit: [150, nil]) %>
    <% else %>
      <%= image_tag "default_profile_picture.png", size: "150x150" %>
    <% end %>
  </div>
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/filtered.html.erb
<p style="color: green"><%= notice %></p>

<h1>Search for Students</h1>
<!-- This comment comment line is visible on the client side. -->
<%# This is an ERB comment and will not appear in the HTML output %>


# <div id="students">
#   <% @students.each do |student| %>
#     <%= render student %>
#     <p>
#       <%= link_to "Show this student", student %>
#     </p>
#   <% end %>
# </div>

<%# link_to "New student", new_student_path %>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Search for Students</h1>

<!-- Display the Search form -->
<%= render 'search', student: Student.new %>


<%= link_to "Show All", students_path(show_all: true), class: "btn btn-secondary mb-3 ms-3 px-5" %>


<% if @students.any? %>
   <h4>Search Results: Total <%= @students.count %> Students</h4>
  <%= render partial: 'results', locals: { students: @students } %>
<% elsif @students.count == 0 %>
    <p>No students found.</p>
  
<% end %>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/saveindex.html.erb
<p style="color: green"><%= notice %></p>

<h1>Search for Students</h1>
<!-- This comment comment line is visible on the client side. -->


<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>